/////// Posts ///////

### Get All posts
GET http://localhost:3000/posts

### Get Post By Id
GET http://localhost:3000/posts/674cbf10e4304a6f3b4b5046

### Get Posts By Sender
GET http://localhost:3000/posts?sender=Sagi

### Create Post
POST http://localhost:3000/posts
Content-Type: application/json

{
"title": "Hello", 
"owner": "Sagi", 
"content": "My Post..."
}

### Update Post
PUT http://localhost:3000/posts/674cbf10e4304a6f3b4b5046
Content-Type: application/json

{
  "title": "Hello",
  "owner": "Kevin",
  "content": "Hello World..."
}


/////// Comments ///////

### Get All Comments
GET http://localhost:3000/comments

### Get All Comments Of A Post ( By PostId )
GET http://localhost:3000/comments?postId=674cbf10e4304a6f3b4b5046

### Get Comment By Id
GET http://localhost:3000/comments/67681119db8020c496af71d2

### Create Comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "674cbf10e4304a6f3b4b5046", 
  "ownerId": "67681393f6dd879fcc2b94aa",
  "content": "This is a great post! Thanks for sharing."
}

### Delete Comment
DELETE http://localhost:3000/comments/676814d1c47b1b691ab32894
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzY4MTM5M2Y2ZGQ4NzlmY2MyYjk0YWEiLCJpYXQiOjE3MzQ4NzQwNTcsImV4cCI6MTczNDg3NzY1N30.aZ-kEwloLRf9oFF2fK6wDUvj1h31Aha63BMPO3X1Tyw

### Update Comment

PUT http://localhost:3000/comments/674f7a28935c3dfc90d9186d
Content-Type: application/json

{
  "postId": "674cbf10e4304a6f3b4b5046", 
  "content": "Great picture!!!.",
  "ownerId": "67680f838c5b9b77add115f0"
}


/////// Users ///////

### Register

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "userName": "guy2",
  "email": "guy2@gmail",
  "password": "123"
}

### Login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "guy2@gmail",
  "password": "123"
}


### Delete
DELETE http://localhost:3000/users/676817143be1c8ebe3ec1bdb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzY4MTcxNDNiZTFjOGViZTNlYzFiZGIiLCJpYXQiOjE3MzQ4NzQ5MDIsImV4cCI6MTczNDg3ODUwMn0.dhKqDFR-UPF66WEXEOolRgUbU2OKbpr-iV3p9jaTR6k